/***************************************************************************//**
 * @file     app_debug_mode_handle.c
 * @version  V1.0.0
 * @author   sz414
 * @date     2022-10-31 21:28:02
 * @brief    This file is automatically generated by CSBMs_Tool, Please complete the code.
 *
 * @copyright Copyright (C) 2020 Chipsea Technologies Corp. All rights reserved.
 *****************************************************************************/

#include "app_inc.h"
#include "comm_protocol.h"
#include "user_config.h"
#include "standard_data_cmd.h"

/*
重要:
1: 寄存器的地址或偏移都是绝对地址
2: DebugMode协议中的字序使用大端，下面的宏用于大端字序生成UINT16，UINT32
*/
#define MAKE_INT8(d0)       ((d0) & 0xff)
#define MAKE_INT16(d0, d1)  (((d0 & 0xff) << 8) | (d1 & 0xff))
#define MAKE_INT32(d0, d1, d2, d3)  (((d0 & 0xff) << 24) | ((d1 & 0xff) << 16) | ((d2  & 0xff) << 8) | (d3 & 0xff))

////////////////////////////////////////////////////
// Command ID definition
#define tagNULL                     0x00
#define tagJumpBoot                 0x01
#define tagReadRegister             0x02
#define tagWriteRegister            0x03
#define tagGrant                    0x04
#define tagCalEnable                0x06
#define tagCalWriteValue            0x07
#define tagFirmwareVersion          0x21
#define tagReset                    0x24
#define tagLifetimeDataCollection   0x25
#define tagSealDevice               0x26
#define tagunSealDevice             0x28
#define tagFullunSealDevice         0x29

//////////////////////////////////////////////
// for Calibration
#include "task.h"
extern Calibration_t cali_param;

////////////////////////////////////////////////////
// privilty_code definition.
static privilty_code_t  privilty_code = PRIVILTY_NONE;
privilty_code_t get_privilty_code(void) 
{
    return privilty_code;
}

////////////////////////////////////////////////////
// Help functon.
// 得到在当前权限下，用户可访问的Memory范围。
//static uint16_t get_user_accessable_range(regtype_t regtype)
//{
    //if( regtype == REGTYPE_MEMORY )
        //return privilty_code == PRIVILTY_DATASHEET ? 0x2004 : (4 + mreg_value_size);
    //else 
        //return reg_value_size;
//}

void handle_debug_mode(uint8_t * data)
{
    TRACE0("handle_debug_command()\n");
    int8_t err_code;
    // TV format until a null terminator is encountered.
    err_code = check_rx_data_packet(data);
    if(err_code == RET_OK){
        parse_rx_data_packet(data);
    }else{ // err handle
        tx_err_code_packet(data, err_code);
    }
}

