/***************************************************************************//**
 * @file     ic_config.h
 * @version  V1.0.0
 * @author   sz414
 * @date     2022-11-23 21:01:05
 * @brief    This file is automatically generated by CSBMs_Tool, Do not edit the content manually
 *
 * @copyright Copyright (C) 2020 Chipsea Technologies Corp. All rights reserved.
 *****************************************************************************/

#ifndef __IC_CONFIG_H__
#define __IC_CONFIG_H__

#define  FMC_DATA_FLASH_BASE_ADDR 0x0000A400

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#pragma pack(push,8)


#pragma pack(pop)

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif //__IC_CONFIG_H__
